=== SimonDevineau/MiddlewarePoject/examination-middleware/src/main/resources/xmlSchemaExamen.xsd
<xs:schema attributeFormDefault="qualified"
  xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation=""></xs:include>
	
	<!-- Un rappel sur les caractères spéciaux en xml.
	Ces  caractères nepeut pas être utilisés, il faut donc les remplacer par leur notations HTML.
	Voici la liste des principaux caractères à éviter et leur équivalent HTML:
	'&' -> "&#38;"
	'<' -> "&#60;"
	'>' -> "&#62;"
	' " ' (double quotes) -> "&#34;"
	'&' (simple quote) -> "&#39;"
	
	Explication du schéma xsd:
	Seule la partie question va être éxpliquée, si toutefois vous aviez plus de question, n'hésitez pas.
	A l'intérieur de la balise question vous retrouvez obligatoirement:
	-une consigne
	-un type de question (soit caseACocher, soit question à choix mutliples, soit une question contenant du code ou une réponse texte)
	-un protocole définissant la façon dont l'élève va être évalué
	
	Si la question est de type codeOuTexte, il y a plusieurs segments, c'est à dire que la question peut être séparée en plusieurs petites parties de texte ou de code. 
	Pour chaque segment, il y a deux types de correction possibles, mais une seul doit être choisi par segment:
	-Syntaxique, qui vérifiera que la réponse a (à un pourcentage) prêt la bonne syntaxe.
	-testCompilationPuisExecution, qui compilera puis executera le code en faisant appel à une méthode de test définit dans le fichier source et dont le nom est précisé entre les balises corrections 
	
	-->
	<xs:element name="examen">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="information">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="enTete">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:string"
											name="titre" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:string"
											name="objet" minOccurs="0" />
										<xs:element type="xs:string"
											name="date" minOccurs="0" maxOccurs="1" />
										<xs:element type="xs:string"
											name="auteur" minOccurs="0" />
										<xs:element type="xs:string"
											name="source" minOccurs="0" /><!-- Le nom du fichier source (fichier ou l'on trouvera le code d'évalutation -->
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="destination"
								minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:string"
											name="UV" minOccurs="0" maxOccurs="1" />
										<xs:element type="xs:string"
											name="module" minOccurs="0" maxOccurs="1" />
										<xs:element type="xs:string"
											name="coefficient" minOccurs="0" maxOccurs="1" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element type="xs:string" name="version"
								minOccurs="0" maxOccurs="1" />
							<xs:element type="xs:string"
								name="commentaires" minOccurs="0" maxOccurs="1" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element type="xs:string" name="preambule"
					minOccurs="0" maxOccurs="1" />
				<xs:element type="xs:string" name="introduction"
					minOccurs="0" maxOccurs="1" />
				<xs:element name="enonce" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="exercice" minOccurs="1"
								maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:string"
											name="introduction" minOccurs="0" maxOccurs="1" />
										<xs:element name="question"
											maxOccurs="unbounded" minOccurs="1">
											<xs:complexType>
												<xs:sequence>
													<xs:element
														type="xs:string" name="consigne" minOccurs="1" />
													<xs:choice
														maxOccurs="1" minOccurs="1">
														<xs:element
															name="codeOuTexte" minOccurs="1" maxOccurs="1">
															<xs:complexType>
																<xs:sequence>
																	<xs:element
																		name="segment" maxOccurs="unbounded" minOccurs="1">
																		<xs:complexType>
																			<xs:sequence>
																				<xs:element
																					name="typeCorrection" maxOccurs="1"
																					minOccurs="1">
																					<xs:simpleType>
																						<xs:restriction
																							base="xs:string">
																							<xs:enumeration
																								value="syntaxeSeulement">
																							</xs:enumeration>
																							<xs:enumeration
																								value="testCompilationPuisExecution">
																							</xs:enumeration>
																						</xs:restriction>
																					</xs:simpleType>
																				</xs:element>
																				<xs:element
																					name="correction" maxOccurs="unbounded"
																					minOccurs="1" type="xs:string">
																				</xs:element>
																			</xs:sequence>
																			<xs:attribute
																				name="id" type="xs:string" use="required">
																			</xs:attribute>
																		</xs:complexType>
																	</xs:element>

																</xs:sequence>
															</xs:complexType>
														</xs:element>
														<xs:element
															name="caseacocher" minOccurs="1" maxOccurs="1">
															<xs:complexType>
																<xs:sequence>
																	<xs:element
																		name="case" maxOccurs="unbounded" minOccurs="1">
																		<xs:complexType>
																			<xs:simpleContent>
																				<xs:extension
																					base="xs:string">
																					<xs:attribute
																						type="xs:string" name="id"
																						use="required" />
																					<xs:attribute
																						name="correction" type="xs:boolean"
																						use="required">
																					</xs:attribute>
																				</xs:extension>
																			</xs:simpleContent>
																		</xs:complexType>
																	</xs:element>
																</xs:sequence>
															</xs:complexType>
														</xs:element>
														<xs:element
															name="choixMultiples" minOccurs="1" maxOccurs="1">
															<xs:complexType>
																<xs:sequence>
																	<xs:element
																		name="choix" maxOccurs="unbounded" minOccurs="2">
																		<xs:complexType>
																			<xs:simpleContent>
																				<xs:extension
																					base="xs:string">
																					<xs:attribute
																						type="xs:string" name="id"
																						use="required" />
																				</xs:extension>
																			</xs:simpleContent>
																		</xs:complexType>
																	</xs:element>
																	<xs:element
																		name="correction" type="xs:positiveInteger"
																		maxOccurs="1" minOccurs="1">
																	</xs:element>
																</xs:sequence>
															</xs:complexType>
														</xs:element>
													</xs:choice>
													<xs:element
														name="protocole" minOccurs="1" maxOccurs="1">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension
																	base="xs:string">
																	<xs:attribute
																		type="xs:string" name="nbEssais" use="optional"
																		default="1" />
																	<xs:attribute
																		type="xs:string" name="version" use="optional" />
																	<xs:attribute
																		type="xs:string" name="duree" use="optional" />
																	<xs:attribute
																		type="xs:string" name="nbPoints" use="required" />
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="id"
													type="xs:string" use="required">
												</xs:attribute>
												<xs:attribute
													name="title" type="xs:string">
												</xs:attribute>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute type="xs:string"
										name="title" />
									<xs:attribute
										type="xs:string" name="id" use="required" />
									<xs:attribute type="xs:string"
										name="langage" use="required" />
									<xs:attribute
										type="xs:positiveInteger" name="coefficient" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element type="xs:string" name="conclusion"
					maxOccurs="1" minOccurs="0" />
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required"></xs:attribute>
		</xs:complexType>
	</xs:element>


</xs:schema>

=== SimonDevineau/MiddlewarePoject/examination-middleware/src/main/resources/examenExample.xml
<?xml version="1.0" encoding="UTF-8"?>
<examen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="xmlSchemaExamen.xsd" id="idBDD">
	<information>
		<enTete>
			<titre>Examen de test pour le middleware</titre>
			<objet>Cet examen est un test pour le Middleware</objet>
			<date>19 décembre 2012</date>
			<auteur>L'equipe GSI</auteur>
			<source>Test.java</source>
		</enTete>
	</information>
	<enonce>
		<exercice langage="" id="e1" title="Un Module de calcul">
			<introduction>Dans un module de calculs, appelé Calculs,
			on développe des fonctions génériques de calculs opérant sur les interfaces précédentes.
			</introduction>
			<question id="q1">
				<consigne>Test de code</consigne>
				<codeOuTexte>
					<segment id="s1">
						<typeCorrection>syntaxeSeulement</typeCorrection>
						<correction>correction1</correction>
					</segment>
					<segment id="s2">
						<typeCorrection>testCompilationPuisExecution</typeCorrection>
						<correction>correction2</correction>
					</segment>

				</codeOuTexte>
				<protocole nbPoints="4"></protocole>
			</question>

			<question id="q2">
				<consigne>Cocher les visibilités existantes en Java</consigne>
				<caseacocher>
					<case correction="true" id="c2">Public</case>
					<case correction="true" id="c1">Private</case>
					<case correction="true" id="c3">Protected</case>
					<case correction="true" id="c4">Package</case>
					<case correction="false" id="c5">Intime</case>
				</caseacocher>
				<protocole nbPoints="2"></protocole>
			</question>
		</exercice>
		<exercice langage="Java" id="2" title="Exercice 2">
			<introduction>Introduction de l'exo 2</introduction>
			<question id="q1">
				<consigne>L'héritage mutiple éxiste-t-il en Java?</consigne>
				<choixMultiples>
					<choix id="c1">Oui</choix>
					<choix id="c2">Non</choix>
					<correction>c1</correction>
				</choixMultiples>
				<protocole nbPoints="2"></protocole>
			</question>
		</exercice>

	</enonce>
</examen>
